import "./globals.css";
import Theme from "@/components/Common/Theme/Theme";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
